language: ruby
rvm:
  - 2.3

cache: bundler

script:
  - bundle install
  - bundle exec jekyll build

deploy:
  provider: pages
  fqdn: blog.gitlocalize.com
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  on:
    branch: master
