name: Deploy

on:
  push:
    branches: [ 'master' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.3'
        bundler-cache: true
    - run: bundle exec rake
    - run: bundle exec jekyll build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cname: blog.gitlocalize.com
        publish_dir: _site
